### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by SolRosenberg** [wdas/reposado#51]
Instead of the --configure option being interactive can repoutil be modified so it can be setup using a one liner? It would be nice to be able to just pass the two paths and the URL to get initial config setup.

**Comment by gregneagle** [comment]
Since reposado's configuration is stored in preferences.plist, you can just create/edit that file any way you'd like: on OS X you could use `PlistBuddy`, or you could even `cat` its contents, which would work on platforms other than OS X. `repoutil --configure` is a helper, but not the only way to create/edit reposado's configuration file.

Many other UNIX tools don't provide any helper for their configuration files and expect the admin to use the text editor of their choice.

**Comment by SolRosenberg** [comment]
Good call I'll just modify that. Thanks Greg.
