### ISSUE TITLE
How can I update complete OS versions via Reposado

### ISSUE THREAD

**Issue by djmcd89** [wdas/reposado#60]
Hi,
I have just setup a reposado server with Margarita on a Debian VM, everything looks quite good so far.
I have the 10.11, 10.12 and 10.13 Catalogs in my preferences.plist and it finds about 500-550 products for each of them so it all seems to be working
However I can't find the "Install macOS High Sierra" update for 10.12 in Margarita.
I have one for 10.11 which has a D behind it and is not listed in Apples branch.
I assume the D stands for deprecated?
Do I have to add a different catalog for full OS version updates or is there anything else I can try?

Thanks

dan

**Comment by gregneagle** [comment]
```
# ./repoutil --products | grep -i "Install macOS High Sierra"
091-14782       Install macOS High Sierra                          10.13.1    2017-10-31 [] (Deprecated)
091-52052       Install macOS High Sierra                          10.13.2    2017-12-06 ['release'] (Deprecated)
091-33271       Install macOS High Sierra                          10.13.2    2017-12-15 ['release'] (Deprecated)
091-62779       Install macOS High Sierra                          10.13.3    2018-01-23 ['testing'] 
091-62780       Install macOS High Sierra                          10.13.3    2018-01-23 ['testing'] 
```

I don't use or support Margarita, but would be happy to help you with reposado and its command-line tools.

With a new setup of Reposado, syncing the 10.13 catalog, you should have the 091-62779 and 091-62780 products.

```
# ./repoutil --info 091-62779
Product:       091-62779
Title:         Install macOS High Sierra
Version:       10.13.3
Size:          5.8 GB
Post Date:     2018-01-23 17:56:56
RestartNeeded: No
Status:        Downloaded
Location:      /disney/.vol/munki/swupd/html/content/downloads/16/14/091-62779
AppleCatalogs:
               https://swscan.apple.com/content/catalogs/others/index-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
Branches:
               testing
HTML Description:
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head><title></title></head>
<body></body>
</html>
```

You might be operating under a misconception, however. These _will not_ upgrade 10.12 machines to 10.13. These products are used by the App Store when downloading the "Install macOS High Sierra" application to a machine. You must use that application (or some other method that uses that application as a starting point) to upgrade machines to 10.13.x.  `softwareupdate` won't do it. To date, the `softwareupdate` tool has never supported doing major OS upgrades.

Since this is not a code issue, further discussion and help should take place on the reposado mailing list: http://groups.google.com/group/reposado

**Comment by djmcd89** [comment]
Ah, great.
I have got 091-62779 and 091-62780.
And I was operating under a misconception, thanks for clearing that up.
I should be able to package new OS versions and deploy them via Munki though so that shouldn't be an issue.
Sorry for posting in the wrong section.
