### ISSUE TITLE
Reposado: BridgeOSUpdateCustomer & macOS Catalina Security Update 2021-002

### ISSUE THREAD

**Issue by FuatHacilar** [wdas/reposado#83]
Hi all

I have an issue with an update on the reposado and an installation of an update on a client.

**BridgeOSUpdateCustomer**
There are 2 updates of BridgeOSUpdateCustomer, 071-29167::1 and 071-29167. The 071-29167 can be selected and assigned to a catalog. for the update 071-29167::1, the same steps are not working. Already removed the update from Productinfo.plist and synced freshly, but the error is the same: Catalog branch doesn't exist!

![Bildschirmfoto 2021-05-17 um 12 17 17](https://user-images.githubusercontent.com/58981285/118474688-9e1a9e80-b70b-11eb-8e91-592ba0ba2b53.png)
![Bildschirmfoto 2021-05-17 um 12 17 23](https://user-images.githubusercontent.com/58981285/118474693-9f4bcb80-b70b-11eb-8d86-7a006472596f.png)

**macOS Catalina Security Update 2021-002**
I can't install this security update on the catalina clients. I think, BridgeOSUpdateCustomer (071-29167::1) is needed for this because when I remove Update server profile from the client, the security update can be downloaded and installed. I get the error: 

Download failed
An error occurred while downloading the selected updates etc.

![Image 17 05 21 at 12 30](https://user-images.githubusercontent.com/58981285/118474825-c99d8900-b70b-11eb-9bb3-803432eddaee.jpg)

any ideas? 

Kind Regards
Fuat

**Comment by gregneagle** [comment]
I don't know what that GUI is that's showing "Catalog branch doesn't exist!" but it's definitely not part of reposado, which is command-line only. So I'd have to guess there's a bug in whatever GUI tool it is you are using. (Maybe Margarita?)

I've definitely added product 071-29167::1 to catalogs successfully using the CLI.

`repoutil add-product 071-29167::1 production`

as an example.

Since reposado is no longer useful with macOS Big Sur, don't expect much in the way of development effort or bug fixes around either reposado or any GUI tool that builds upon it...

**Comment by FuatHacilar** [comment]
Hi Greg

I could add the update manually to the CatalogBranches.plist and now is activated on the GUI.
We're setting up an apple caching server so we've to maintenance reposado still for a while.

thanks for your help, greets
Fuat
